### PR TITLE
Fix logs

### LINKED ISSUE #36: Hide data in logs
Emitting the data to logs is useful for debug and certain use caes, however there are some customers or scenarios when this is not allowed.

Request to add an option to "Suppress logging data" checkbox that would prevent the console.log action.

### PR DESCRIPTION
**Pull request by jhorbulyk**
Fixes #36

### CODE REVIEW

**Review by denyshld — APPROVED** [review]

File: lib/triggers/receive.js [hunk 1]
```diff
@@ -23,7 +24,7 @@ exports.process = async function receive(msg) {
       msg.body._additionalUrlPath = msg.additionalUrlPath;
     }
 
-    this.logger.info('Updated body: \n', JSON.stringify(msg.body));
+    this.logger.debug('Updated body: \n', JSON.stringify(msg.body));
```
Comment (drobiazko) [inline lib/triggers/receive.js:27]: IMO we must never print data, even in debug level.

**Review by drobiazko — CHANGES_REQUESTED** [review]

File: lib/triggers/receive.js (hunk 1 above)
Comment (khanzadyan) [reply lib/triggers/receive.js:27]: But what if customer wants to debug the incoming data?

Comment (drobiazko) [reply lib/triggers/receive.js:27]: Next time some other developer will change the level to info for debugging purpose and will forget to change it back and so introduce the printing of data back to production

Comment (drobiazko) [reply lib/triggers/receive.js:27]: > But what if customer wants to debug the incoming data?

The customer can't change the log level anyway. It can only be done by developer. If done, it is done for all customers using the component. That's why printing of data must be forbidden.

Comment (khanzadyan) [reply lib/triggers/receive.js:27]: would have been nice to switch on/off this per contract or workspace.

Comment (drobiazko) [reply lib/triggers/receive.js:27]: Yes, but we don't have this possibility atm. We need to fill a product issue for that. Until it is there, we need to forbid logging data.

Comment (jhorbulyk) [reply lib/triggers/receive.js:27]: > IMO we must never print data, even in debug level.
Strongly disagree.

Comment (drobiazko) [reply lib/triggers/receive.js:27]: From perspective of a component developer I would also disagree. But a customer who cares about data protection does disagree with the developer. It's about our compliance.

Comment (drobiazko) [reply lib/triggers/receive.js:27]: @jhorbulyk since we agreed with @juhrmacher on the policy for logging data in components may I ask you to adapt your PR by removing the logging of data completely?

**Review by PaulAnnekov — APPROVED** [review]
